### PR TITLE
Add Shredify app

### PR DESCRIPTION
**Pull request by DanielDarrenJones**

### CODE REVIEW

**Comment by joshmanders** [comment]
Where is this using Tailwind? Looking at source I can't find anything related to tailwind, only UI Kit.

**Comment by m1guelpf** [comment]
@joshmanders It's the app that's using Tailwind, according to Twitter. Maybe we should add a new section and link directly to the app?

**Comment by joshmanders** [comment]
Yeah it's kind of confusing

**Comment by joshmanders** [comment]
Is there someway to show more screenshots than the one little one on the homepage? This is kind of a tough thing because people will want to see how things are done, and because the apps themselves use tailwind and not anything you can't see without first downloading is tough.

**Comment by DanielDarrenJones** [comment]
@joshmanders I could do a blog post about it?

**Comment by joshmanders** [comment]
@DanielDarrenJones that could work. Then just link to your blog post about how you used tailwind to develop the app. That would feel less spamish.

**Comment by DanielDarrenJones** [comment]
Awesome, ill get a post written up this week ;)

**Comment by joshmanders** [comment]
Cool. I'm gonna close this PR you can just open a new one when that's ready. Appreciate it @DanielDarrenJones. Can't wait to read the article too. I'm interested in how you did it.

**Pull request closed without merging**
