### PR TITLE
Add Multi Theme and Windmill

### PR DESCRIPTION
**Pull request by estevanmaito**
Add [Tailwind CSS Multi Theme](https://tailwindcss-multi-theme.now.sh/) to plugins

and [Windmill Dashboard](https://windmill-dashboard.vercel.app/) to templates.

And I have a question: where would [Tailwind Starter Kit](https://tailwind-starter-kit.now.sh/) fit? It is a [library of components](https://tailwind-starter-kit.now.sh/docs/alerts), but it has also a [learning  guide](https://tailwind-starter-kit.now.sh/learn).

Should I place two entries, one for Learning (pointing to the guide) and one for Templates/themes (pointing to the components)? Or do you think there is a category which fits it?

### CODE REVIEW

**Comment by innocenzi** [comment]
I think the Tailwind Starter Kit would fit best in the UI Libraries & Components category since it's advertised as such and looks like it is its main purpose. 

I personally would like to see only one entry, but I'll let @joshmanders give his thoughts about this. 

Unrelated, but I added `tailwindcss-multi-theme` to the Alternatives section of `tailwindcss-theming`. 👍

**Comment by joshmanders** [comment]
I'd agree with @innocenzi

**Comment by estevanmaito** [comment]
I checked the UI Libraries section and found that there is already a Tailwind Starter Kit entry, which I think fits more as a library of components.

My starter kit is more of a starter for learning, hence the playground under every component. What do you guys think if I place it under Learning as a "Component or Page Tutorial". Then I would link directly to the [getting started tutorial](https://tailwind-starter-kit.now.sh/learn), which in fact is a getting started with Tailwind CSS and not the components. One entry, would avoid colliding with the existing one and in the end it's also a tutorial.

> Unrelated, but I added tailwindcss-multi-theme to the Alternatives section of tailwindcss-theming.

Nice! I also mention `tailwindcss-theming` as an alternative

**Comment by innocenzi** [comment]
I think it would be fine if it was under the Learning > Component or Page Tutorial category, indeed. Do you want to make another pull request, or to commit to this one?

**Comment by estevanmaito** [comment]
This one can be merged as is.

I'm creating another plugin, so I can PR them together later this week.

**Pull request merged**
