### PR TITLE
add(library): Tailwind UI Kit

### PR DESCRIPTION
**Pull request by aqkhan**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Tailwind UI Kit | https://tailwinduikit.com |

600+ components & 30 templates using Tailwind CSS with React, Angular, and Vue integrations & interactions.

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by joshmanders** [comment]
I'm pretty sure there's a trademark violation in the name of this kit.

**Comment by aqkhan** [comment]
@joshmanders 

> I'm pretty sure there's a trademark violation in the name of this kit.

There's no "Tailwind UI" trademark registered in the United States, we've checked. Please do point out if you know something that we don't.

FYI, the [tailwind trademark](https://trademarks.justia.com/857/84/tailwind-85784495.html) is registered to DMO INCORPORATED.

**Comment by joshmanders** [comment]
I don't remember exactly, I just know I've seen @adamwathan mention on Twitter a few times to please not use Tailwind UI in the name of projects. So it may be of issue. I'd probably reach out to him if I were you.

**Comment by aqkhan** [comment]
He can tell anything he wants, if there's a TM infringement, we need to know. We researched and nothing came out of it.

Also, Is this guy is a gatekeeper of what people can make with open source stuff? We have an entirely different product.

FYI

Screenshot 2021-01-07 at 12 35 18 AM

**Comment by joshmanders** [comment]
After having talked to Adam, this is in violation of Tailwind Labs trademark.

> Also, Is this guy a gatekeeper of what people can make with open source stuff? We have an entirely different product.

Build whatever you want, just don't use someone else's trademark.

**Pull request closed without merging**
