### PR TITLE
add(tools): Tailscan

### PR DESCRIPTION
**Pull request by ErwinAI**
| Name                 | Link                 |
| -------------------- | -------------------- |
| _Tailscan_ | _Tailscan.com_ |

_Ultimate devtools for Tailwind CSS v3 with ability to convert CSS to Tailwind CSS classes_

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by innocenzi** [comment]
The item is marked as accessible online, but it doesn't seem to be, is it? It's simply a browser extension?

@joshmanders what do you think of requiring paid stuff to have something like 💰 (or another emoji)?

**Comment by joshmanders** [comment]
> The item is marked as accessible online, but it doesn't seem to be, is it? It's simply a browser extension?
> 
> @joshmanders what do you think of requiring paid stuff to have something like 💰 (or another emoji)?

I'm honestly on the fence about even allowing paid stuff. What do you think? If we allowed paid, I agree with an emoji, but I trust you and your call.

**Comment by innocenzi** [comment]
I think some paid tools are fine because they provide value. But I would prefer them to be clearly labeled as commercial in the list. I think we can merge this one and I should do one big cleanup like last time soon. 👍

**Comment by innocenzi** [comment]
@ErwinAI please remove the glob emoji and I can merge 👍

**Comment by ErwinAI** [comment]
> @ErwinAI please remove the glob emoji and I can merge 👍

Will do!

Thank you for both maintaining this repo 🙏

There are some other tools that also use the globe emoji but aren't accessible online by the way. Bit of an ambiguous emoji.
As to providing value, most browser extensions are paid because it gives a bigger incentive to stay relevant and up-to-date. Fair though to label them as such (💲 emoji?). I'll have more things to submit to this list that are free soon :)!

**Comment by innocenzi** [comment]
> There are some other tools that also use the globe emoji but aren't accessible online by the way. Bit of an ambiguous emoji.

You're right, I'll make sure to clean that up. Thanks for your contribution!

**Review by innocenzi — APPROVED** [review]

**Comment by joshmanders** [comment]
> most browser extensions are paid because it gives a bigger incentive to stay relevant and up-to-date.

My biggest worry is that people will start using this as a place to market their products. Useful tools that happen to cost something are understandable, but we'll have to be very cautious about letting paid stuff into the list.

@innocenzi maybe we should add more info about paid to the contributions guide and how they'll be handled?

**Pull request merged**
