### PR TITLE
add(websites): myjourney.page and chriswray.dev

### PR DESCRIPTION
**Pull request by cwray-tech**
These are a couple of websites I built with Tailwind CSS and Tailwind UI.

| Name                 | Link                 |
| -------------------- | -------------------- |
| _MyJourney_ | _https://myjourney.page/_ |
| _Chris Wray_ | _https://chriswray.dev/_ |

These are two websites that I have recently released using Tailwind CSS. If you don't think they are awesome you don't have to add them to the list haha.
---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by innocenzi** [comment]
They do look quite good, but they don't particularly stand out to me. In order to prevent what happened before the cleanup, I don't think we should add them to the list. 

Pinging @joshmanders for the final decision on this one.

**Comment by joshmanders** [comment]
I agree, @innocenzi.

**Comment by cwray-tech** [comment]
Thanks, @joshmanders, and @innocenzi! Hopefully, this wasn't annoying to you and I understand if you have had issues with a ton of submissions in the past.

**Comment by innocenzi** [comment]
No worries. 👍

**Comment by joshmanders** [comment]
No worries at all. We actually don't get a lot of submissions. Maybe 1-2 a week. Totally appreciate your understanding of trying to keep the list from becoming overbearing. Feel free to submit anything else, plugins, etc.

**Comment by cwray-tech** [comment]
@joshmanders thank you! These were my first Tailwind projects so I was pretty excited haha! Have a great day.

**Comment by dector** [comment]
@innocenzi Let's make a separate long list for those Tailwind-related websites that can't be included here? Would be nice to be able to browse them anyway. :)

**Comment by innocenzi** [comment]
Well you're free to make a separate list, sure. But an `awesome` repository is not really the place for this. Maybe you're looking for something like https://builtwithtailwind.com/?

**Comment by dector** [comment]
Good point, thanks.

**Pull request closed without merging**
