### PR TITLE
added resources

### PR DESCRIPTION
**Pull request by michael-andreuzza**
| Name                 | Link                 |
| -------------------- | -------------------- |
| _Resource name here_ | _Resource link here_ |

_Resource description here_

---

- [✔] My item is in the right category
- [✔] My item is logically grouped below similar items
- [✔] My item's name and description respects the conventions of the list
- [✔] My item is awesome
- [✔] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [✔] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by innocenzi** [comment]
Thank you for your contribution, but I'm not comfortable adding all of your paid packages in there. You barely made an effort regarding the PR and it seems you didn't read the contributions guidelines either.

**Comment by michael-andreuzza** [comment]
I did read it fully the contribution this time, I was rushing the first time. They are not all paid products, the only paid is Lexington Themes and it has 100% free options. 

The others 4 resources are 100% free, in fact, three of them are open source...
On that list you have paid products, I don't understand what makes it different to mine ones.

Have a good day

**Comment by innocenzi** [comment]
Maybe you read them, but you still didn't apply them. You didn't respect the PR template either. In a matter of transparency, here's what I found wrong:

- The PR template still has placeholder data
- The PR title doesn't respect the required format
- The PR contains changes to `.vscode/settings.json`
- You did not position your items at the end of their categories
- Some of the item descriptions do not respect the required syntax
- Windstatic seems to be work-in-progress
- You did not link directly to the repositories of the projects that are open-source
- I don't think Swissfolio has the qualities to be in this list
- I don't understand why AstroSAAS has a screenshot of Linear

To be fair, I like the most of the items you submitted. Some of them could belong to the list, but Awesome Tailwind CSS has already a lot (too much) of content and I am planning on specifically marking paid products as such in the future, in the meantime I'd like to avoid adding new ones.

If you didn't understand the guidelines and have suggestions to improve their clarity, I'm willing to listen to them. In the meantime, I'm not willing to accept PRs that did not put the minimum amount of efforts we asked for.

**Comment by michael-andreuzza** [comment]
You don't need to feature the projects, it's fine. I just wanted to share some free stuff I made for the community. 

Just some things I haven't seen clear was:
_- The PR template still has placeholder data_
I added 5 products, did you wanted me to add all 5 there?

_-The PR title doesn't respect the required format_
According to the contributions guidelines this says the next:
_"You can name your pull request and commits however you want, but for clarity, [conventional commits](http://conventionalcommits.org/) are welcome. Pull request will be squashed upon merge."_
I wrote "added resources"

_You did not position your items at the end of their categories_
I haven't seen this on the contributions guidelines...


_Some of the item descriptions do not respect the required syntax_
Personally, I don't see any issue with the syntax...? Short and explicit.

_Windstatic seems to be work-in-progress_
I am adding more and more when I have them ready.

_You did not link directly to the repositories of the projects that are open-source_
I haven't found information about what links should be used.

_ don't understand why AstroSAAS has a screenshot of Linear_
Is just a screenshot...

I did understood most of it, but for example some points that you mentioned like the links, have to be to the repo, and it has to be at the I can't find them.

Thank you for taking your time.

/Mike

**Comment by joshmanders** [comment]
@michael-andreuzza 
> _You did not position your items at the end of their categories_ I haven't seen this on the contributions guidelines...
[> ](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md?plain=1#L10)

> _You did not link directly to the repositories of the projects that are open-source_ I haven't found information about what links should be used.

We will update this in the guidelines. If it's open source, link to the repository not the website.

With regards to the free components, they are just not awesome enough... There's sooo many inconsistencies in the components, they look rushed to generate "free snippets" that people will share/use as a lead magnet to your paid themes which I admit, look awesome. Just the free ones aren't good enough to take up space.

You may think they're awesome, but unfortunately we have standards not just for the Awesome Tailwind CSS repo itself, but set by the broader Awesome List community, that we have to abide by to stay listed on the master Awesome list.

@innocenzi we should re-evaluate the non-free links. We need to prune content and paywall blocked stuff (sans official Tailwind Labs stuff) should be the first to go, IMO.

**Comment by innocenzi** [comment]
> we should re-evaluate the non-free links. We need to prune content and paywall blocked stuff (sans official Tailwind Labs stuff) should be the first to go, IMO.

Definitely agree we have to do something about these. I'd love to do a complete clean-up of the list again, but I've yet to find the time 😔

**Comment by joshmanders** [comment]
> > we should re-evaluate the non-free links. We need to prune content and paywall blocked stuff (sans official Tailwind Labs stuff) should be the first to go, IMO.
> 
> Definitely agree we have to do something about these. I'd love to do a complete clean-up of the list again, but I've yet to find the time 😔

I'm putting it in my todo list next week to go through and clean stuff up. I'll submit a PR for you to review when I'm ready.

**Comment by michael-andreuzza** [comment]
@joshmanders 

> We will update this in the guidelines. If it's open source, link to the repository not the website.
> 
> With regards to the free components, they are just not awesome enough... There's sooo many inconsistencies in the components, they look rushed to generate "free snippets" that people will share/use as a lead magnet to your paid themes which I admit, look awesome. Just the free ones aren't good enough to take up space.

Hey Josh, they are not rushed..., the idea is to be aesthetic, simple as it gets, a starting point.

But hey, as mentioned no need to feature them. 

Thank you for taking your time.

/Mike

**Pull request closed without merging**
