### PR TITLE
add(components): Preline UI 

### PR DESCRIPTION
**Pull request by RabbITCybErSeC**
| Name                 | Link                 |
| -------------------- | -------------------- |
| _Preline UI_ | _[Resource link here](https://preline.co)_ |

Preline UI is an open-source Tailwind CSS components library for any needs. Comes with UI examples & blocks, templates, plugins, Figma design system and more. For:  HTML React Vue 

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by innocenzi — CHANGES_REQUESTED** [review]
Can you update the description to fit the guidelines please?

**Comment by RabbITCybErSeC** [comment]
hi @innocenzi , can you clarify what should be changed on the description?

**Comment by joshmanders** [comment]
@RabbITCybErSeC make sure to read the description sections of the [Contribution Guide](https://github.com/aniftyco/awesome-tailwindcss/blob/master/CONTRIBUTING.md#formats-naming-conventions-and-descriptions).

**Comment by RabbITCybErSeC** [comment]
@innocenzi  @joshmanders  hopes this fixes the issue.

**Review by innocenzi — APPROVED** [review]

**Pull request merged**
