### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LorenzoBloedow**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Tailwind Shades For Custom Colors | https://github.com/LorenzoBloedow/tailwind-shades-for-custom-colors |

_Automatically generate shades for your custom colors defined under `theme.extend.colors` in the `tailwind.config.js` file._

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by innocenzi** [comment]
I would put that under the utility category, what do you think?

**Comment by LorenzoBloedow** [comment]
You're right, that makes more sense.

**Comment by joshmanders** [comment]
ping @LorenzoBloedow. If no response/update this PR will be closed Friday, December 16th 2022.

**Comment by LorenzoBloedow** [comment]
Done

**Comment by innocenzi** [comment]
@LorenzoBloedow Since your tool is pretty new, not yet popular, since there are alternatives on this list and because you didn't really feel like following the guidelines, I'm going to go ahead and close this PR.

Feel free to re-open when your plugin gets more popular, and please follow the guidelines if you do so, I'll be happy to review your PR again!

**Pull request closed without merging**
