### PR TITLE
Add Tailwind Blocks

### PR DESCRIPTION
**Pull request by mertJF**

### CODE REVIEW

**Comment by Log1x** [comment]
This is dope.

**Comment by joshmanders** [comment]
Hey @mertJF I haven't been able to access this in a while, is it dead?

**Comment by mertJF** [comment]
I am going to create a repository for it and update dead links too. Let you know when it is ready. Thanks for your interest.

**Comment by joshmanders** [comment]
> I am going to create a repository for it and update dead links too. Let you know when it is ready. Thanks for your interest.

Excellent, please make sure to submit a PR right away when it's ready, I went to it today to use some stuff and couldn't access it. Got sads.

**Comment by mertJF** [comment]
Hello again, I've submitted a new PR. Here is, https://github.com/aniftyco/awesome-tailwindcss/pull/243

**Pull request merged**
