### PR TITLE
add(templates): k-wd dashboard

### PR DESCRIPTION
**Pull request by Kamona-WD**
| Name                 | Link                 |
| -------------------- | -------------------- |
| _K-WD Dashboard_ | _https://github.com/Kamona-WD/kwd-dashboard_ |

_Resource description here_

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by joshmanders — CHANGES_REQUESTED** [review]
Great start to a template, but it is kind of lacking right now. I'm not denying the PR but we're not gonna merge it in until the template has been fleshed out some more as right now it's not very "awesome".

Please feel free to ping us again on this PR when you've got more of the components and pages filled in.

**Comment by Kamona-WD** [comment]
thanks

**Comment by joshmanders** [comment]
Hey @Kamona-WD I'm closing this PR. Go ahead and open another when you've completed the template.

**Comment by Kamona-WD** [comment]
Alright

**Pull request closed without merging**
