### PR TITLE
Add tool vscode-inline-fold

### PR DESCRIPTION
**Pull request by tordans**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Inline Fold - VSCode Extension | https://github.com/moalamri/vscode-inline-fold |

I don't know what 
> NOTICE: this extension is still under active development!

means in detail, so I don't know if @moalamri would call this extension 'awesome' at this stage. Therefore, this is just a draft PR for now. If anyone thinks it should be in the list today, please weight in.

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [ ] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by innocenzi** [comment]
That extension looks very useful for VSC + Tailwind CSS users, but it no longer seems to be in "active" development. Let's wait a few days and see.

**Comment by moalamri** [comment]
Hey guys,
Thanks for featuring this. It is still under active development, not so active tho, I barley find time with some work-related tight deadlines :D.
I agree with you not to 'awesome' it now as it still lack the support for most of template literal use-cases.
I hope with the release of v0.2.0 it then could be "out of development".

**Comment by joshmanders** [comment]
Moreso is this even something related to Tailwind CSS and not just something that helps working with Tailwind CSS?

If we add this, does that mean we allow other semi-related things?

**Comment by innocenzi** [comment]
@joshmanders very valid concerns, but I think the extension could be particularly useful for working with Tailwind CSS, and I wouldn't be surprised if it was developed with that in mind but made less specific because it could be useful for other things too. 

In my opinion it's fine to let it be in "IDE extensions" once it's finished, but it's up to you 👍

**Comment by moalamri** [comment]
@joshmanders It is the main use case, as it was the reason I developed it, but since it could be useful in other use cases I didn't limit it, and I gave users the options to tweak settings and gave it a generic name.
So, I agree with both of you about this concern, and I wouldn't add it to be directly related to Tailwincss it self, but more of "a tool that could be helpful" when working with Tailwindcss.

**Comment by joshmanders** [comment]
Well if it was developed with Tailwind in mind, then I say go for it if you think it's acceptable, @innocenzi!

**Comment by joshmanders** [comment]
This has evolved to barely even be noticeable to have anything to do with Tailwind so I'm going to opt out of including it. We don't want to set a precedence for "You can use this for tailwind even though it's not a tailwind thing" list of stuff, otherwise we'd have to include ridiculous stuff.

**Pull request closed without merging**
