### PR TITLE
add(plugins): Downwind CSS Easings

### PR DESCRIPTION
**Pull request by dance2die**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Downwind CSS Easings | https://github.com/downwindcss/easings |

Extends `transition-timing-function` utilities.

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by dance2die** [comment]
**Side Note**: `Downwind CSS` is my GitHub organization. Not a typo of Tailwind CSS

**Review by innocenzi — APPROVED** [review]

**Comment by innocenzi** [comment]
Can you resolve the conflicts?

**Comment by dance2die** [comment]
> Can you resolve the conflicts?

I merged upstream master, but so many files have changed :sweat:   
Should I abort this PR and create a new one?

**Comment by innocenzi** [comment]
Not sure why it closed the PR, but I updated your branch, and you can open a new PR. 👍

**Comment by dance2die** [comment]
Thank you for the review @innocenzi 
A new PR is #360

**Pull request closed without merging**
