### PR TITLE
Remove broken links

### PR DESCRIPTION
**Pull request by spekulatius**
Hey,

I've noticed a two broken links while looking through the list of apps and website at the end.

Cheers,
Peter

### CODE REVIEW

**Review by innocenzi — APPROVED** [review]

**Comment by innocenzi** [comment]
Good looking out, thank you!

**Comment by spekulatius** [comment]
👍️

**Comment by joshmanders** [comment]
Thanks Peter!

**Comment by spekulatius** [comment]
No problem @joshmanders! Happy to help out!

**Pull request merged**
