### PR TITLE
Add custom-forms plugin

### PR DESCRIPTION
**Pull request by praveenperera**

### CODE REVIEW

**Comment by praveenperera** [comment]
Yes @joshmanders I'll make that change.

I'm also thinking we should wait a lit bit before merging it in since its under active development still: https://twitter.com/adamwathan/status/1141507850507870208

**Comment by joshmanders** [comment]
@praveenperera good idea. Just ping me on this PR when it's ready and we can merge it in.

**Comment by joshmanders** [comment]
@praveenperera what are your thoughts on merging this in, should we still wait or no?

**Comment by praveenperera** [comment]
Ya I think we should just go ahead and merge it in.

He has some docs up for it too: https://tailwindcss-custom-forms.netlify.com/

**Comment by joshmanders** [comment]
@praveenperera done. Thanks for the contribution!

**Pull request merged**
