### PR TITLE
Add `UptimeMate` to Apps & Websites

### PR DESCRIPTION
**Pull request by frankspin89**

### CODE REVIEW

**Comment by hawezo** [comment]
That website is good looking but it looks like the Apps & Website category is just becoming an ad space. There are already some sites with that kind of layout in it, and I don't know if we should continue to add everything just because it looks good.

Thoughts @joshmanders?

**Comment by joshmanders** [comment]
@hawezo I'm not sure. The point of the Apps & Websites section is to show sites that actually use Tailwind, so I don't think it's fair to just stop accepting PR's because the list is getting big. If we don't accept sites that use Tailwind, then we should remove all.

Maybe we should audit the list and remove any that seem dead/inactive to make room for newer ones? I'm not sure.

**Comment by hawezo** [comment]
I get the point where it's not fair and I totally agree. What made me think this is the fact that this specific PR was quite effortless (no title, no description) and it looks like the author just want to publish its site. I may be wrong though, I mean no offense to @frankspin89 if it wasn't your intention. 

That said, I believe that Tailwind will grow way bigger than it is right now, and as a result this repository will possibly get more PRs like this one. I don't think we should accept all of them, and I think that the Apps & Website category should have specific criteria (not to be discussed on this issue though). As to how to make them fair, I don't know yet. 

It's up to you to accept this one, I'm not against it, but you have my thoughts for the future. ^^

**Comment by joshmanders** [comment]
I agree we need to come up with something. We'll accept this one and formulate a plan.

**Pull request merged**
