### PR TITLE
add(plugins): `tailwindcss-themeable`

### PR DESCRIPTION
**Pull request by upupming**
| Name                 | Link                 |
| -------------------- | -------------------- |
| _Tailwind CSS Themeable_ | _https://github.com/upupming/tailwindcss-themeable_ |

_Resource description here_

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by joshmanders — CHANGES_REQUESTED** [review]
Please follow the template and contribution guidelines.

**Comment by upupming** [comment]
> Please follow the template and contribution guidelines.

Sorry for that mistake, I have updated the description as the template and contribution guidelines, thanks!

**Review by innocenzi — APPROVED** [review]

**Comment by innocenzi** [comment]
LGTM now 👍

**Review by joshmanders — APPROVED** [review]
Thank you!

**Pull request merged**
