### PR TITLE
awesome-list compliance update

### PR DESCRIPTION
**Pull request by jthegedus**
The creator of `awesome-lists` has released a tool for [linting awesome-lists](https://github.com/sindresorhus/awesome-lint) before they can be added to the parent [awesome-list](https://github.com/sindresorhus/awesome).

This PR brings the README up to the rigorous standard of the linting tool. There are some items that only the GitHub repo owners can perform such as updating the repo Topics.

Fixed issues:

- [x] [awesome-lint](https://github.com/sindresorhus/awesome-lint) via GitHub Actions
- [x] fix `'` use
- [x] remove dead urls (manually checked each URL, see next point)
- [x] ignore false-positive `no-dead-urls` awesome-lint error caused by https://github.com/sindresorhus/awesome-lint/issues/89
- [x] removed tables for legend and instead moved them as a horizontal list to the top of each section. One of the emojis was causing the markdown table formatting to be inconsistent which threw an error with `awesome-lint`. This is more simple, easier to read and takes less vertical space so better positioned at the top of each section.

~Outstanding issues:~

<details>
<summary>not valid</summary>

```
  ✖  1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome-github
  ✖  1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github
```

</details>

### CODE REVIEW

**Comment by joshmanders** [comment]
What do you think of the changes @hawezo?

**Comment by hawezo** [comment]
Looks good to me. I do prefer the legends that way, too. Thanks for cleaning up! 👍 

@jthegedus, related to those two errors:

```
✖  1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome-github
✖  1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome-github
```

I think that is because you ran the linting tool from your fork, which doesn't have the topics.

**Comment by jthegedus** [comment]
@hawezo Yes, you are right.

**Comment by jthegedus** [comment]
@joshmanders Resolved conflicts

**Comment by joshmanders** [comment]
Thanks @jthegedus!

**Comment by jthegedus** [comment]
@joshmanders pleasure! :smile:

**Pull request merged**
