### PR TITLE
change(tools): update Gradient Designer name, url and description

### PR DESCRIPTION
**Pull request by jenstornell**
I updated the Gradient Designer to version 2, which also has all the colors from Tailwind 2.

A minor change has been done to the name. I removed "Tailwind" but it's still a gradient generator for Tailwind.

### CODE REVIEW

**Comment by joshmanders** [comment]
Is there any difference between these two projects outside of name and url change? Is the old one focusing on Tailwind v1, and new one Tailwind v2?

If so maybe we should have them both in the list as v1 is still being used by many people. What are your thoughts @innocenzi?

**Comment by innocenzi** [comment]
Took a look, and it doesn't seem like there are changes between the two. I'd say we only keep the new version, unless I missed stuff that is Tailwind v1-specific in the first version, in which case I'd agree we should keep them both in the list for now.

**Comment by joshmanders** [comment]
@jenstornell can you clarify?

**Comment by jenstornell** [comment]
@innocenzi @joshmanders 

Yes, you have a point. Tailwind 1 users may still like the old version of Gradient Designer better.

**I've put it back now and it's available here:**
https://gradient-designer.csspost.com/v1.0/

**Review by innocenzi — APPROVED** [review]

**Comment by innocenzi** [comment]
LGTM 👍

**Review by joshmanders — APPROVED** [review]
Thanks @jenstornell!

**Pull request merged**
