### PR TITLE
Add Sage – WordPress starter theme

### PR DESCRIPTION
**Pull request by knowler**
We just added Tailwind as a frontend preset for Sage.

### CODE REVIEW

**Comment by joshmanders** [comment]
I checked the repo linked and it links directly to sage's repo but there's nothing in there that says the project uses tailwind, infact it's using bootstrap... Is there a repo that specifically showcases that tailwind is used somewhere? I don't want to link global projects that have plugins or presets that can be for tailwind, if they don't have it in the main repo.

**Comment by joshmanders** [comment]
After digging around submitting this article is fine though. https://roots.io/guides/how-to-setup-tailwind-css-in-sage/

**Comment by knowler** [comment]
Sounds good. I wrote the article, so I'm not complaining. 😂

**Comment by joshmanders** [comment]
Yeah probably be better put there. I think more categories are gonna be needed, so I'll probably go through that.

**Comment by joshmanders** [comment]
Awesome, thanks @knowler!

**Pull request merged**
