### PR TITLE
add(components): kokonutUI

### PR DESCRIPTION
**Pull request by dorianbaffier-dev**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Kokonut UI | https://kokonut.dev/ |

A collection of modern, interactive, customizable UI components
---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by joshmanders** [comment]
Thanks for your submission but unfortunately there's just not enough to add it right now. You can resubmit again in the future when there's more components.

**Comment by dorianbaffier-dev** [comment]
I've just added a bunch of components (10+) @joshmanders, what do you think?

**Comment by innocenzi** [comment]
@dorianbaffier-dev Let's re-submit this in a few months if it has gained some traction 👍

**Comment by joshmanders** [comment]
@dorianbaffier-dev while these components are shaping up to be indeed pretty awesome, you have 5 components but in a few variations and just started building this a week ago... Unfortunately we can't be a catch all for everything Tailwind related and a dumping ground for new things that could be abandoned soon after beginning, the list is after all AWESOME things and we have standards both for the list and that we must adhere to as to not lose our listing on the main awesome list. 

Like @innocenzi has stated, keep building them out adding more component types and see where things are after the new year and if there's more components and still being developed, then we'll allow it.

**Comment by kokonutd** [comment]
Hi @joshmanders, pinging here this since few months passed. The project is still active and have much more content as well. Let me know if that's valid on your side!
Thank you

**Comment by joshmanders** [comment]
@kokonutd Submit a new PR.

**Pull request closed without merging**
