### PR TITLE
Added meraki ui blog

### PR DESCRIPTION
**Pull request by khatabwedaa**
it single page for blog site design it by @merakiui Team.

### CODE REVIEW

**Comment by hawezo** [comment]
Hi, sorry but this is not the correct section. The description is not written in a correct english. 
 And it also seems that the "UI kit" is not yet finished. Its repository title even has a typo. 

@joshmanders

**Comment by khatabwedaa** [comment]
in any section i should put it , :full_moon_with_face: and my english not bad :smiley: , i know the "UI kit" not finished , but this template finished i want people try it and if have any issue to fixed before i release the "UI kit" :tada: ...

**Comment by joshmanders** [comment]
Along with what @hawezo said, I really don't see much here, the blog repo is fine, you can link that, but the whole description reads as an advertisement for a "UI Kit" that is just 6 html files with a some tailwind classes, nothing to showcase the components, no documentation, nothing.

You can add a link for the blog example, but reword the description so it's not and advertisement, and when "meraki ui" has more substance submit a new PR and we'll assess again.

**Comment by khatabwedaa** [comment]
okay thanks @joshmanders :+1:  :smile:

**Pull request closed without merging**
