### PR TITLE
add(tools): updrafts.app

### PR DESCRIPTION
**Pull request by smeijer**
| Name                 | Link                 |
| -------------------- | -------------------- |
| updrafts.app | https://updrafts.app/ |

An online no-code drag and drop editor to build Tailwind CSS based elements or full designs. The idea is similar to `tailwind play`, _(design online with instant feedback and sharable links)_, but instead of needing to write code, the user uses a drag-and-drop based interface and property pickers.

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] I have read and followed the [contribution guidelines](.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by reslear** [comment]
@joshmanders @innocenzi maybe you should somehow mark paid tools? ex 💵

**Comment by joshmanders** [comment]
> @joshmanders @innocenzi maybe you should somehow mark paid tools? example dollar emoji 💵

That's a good idea, what do you think @innocenzi?

**Comment by smeijer** [comment]
I'm all in for the `paid tool emoji`. Updrafts.app also has a generous free version tho. So a `free plan emoji` would than be a welcome addition as well.

**Comment by innocenzi** [comment]
@joshmanders I agree, how about we merge this, and I'll go through the whole list later to add the emojis?

**Review by joshmanders — APPROVED** [review]
Sounds good to me! 👍

**Pull request merged**
