### PR TITLE
Clean-up: fixes, organization, descriptions

### PR DESCRIPTION
**Pull request by hawezo**
I think this repository needs some cleanup and reorganization. I'm obviously open to discussion about any modification I have made. :)

- [x] Fixed `awesome-lint` errors (those fixable by me at least, missing errors are bugs or repo-wide issues)
- [x] Add description for each list item, because names alone or not very descriptive.
- [x] Reorganize items, because some are not in the good categories.
- [x] Reorganize categories, because some are too vague and other are too specific.
- [x] Remove the `Add your item` for each category. I think having this below each category is not necessary:
  - It makes the contributor skip the `CONTRIBUTING` part at the end of the `README`. 
  - It's very repetitive.
- [x] Remove deprecated items and dead links:
    - [Webpack Starter Project](https://github.com/tailwindcss/webpack-starter) - Deprecated.
    - [Adds Tailwind CSS to your Ember app or addon](https://github.com/embermap/ember-cli-tailwind) - Deprecated.
    - [Create React Native App Tailwind](https://github.com/taylorbryant/crna-tailwind) - It's "work-in-progress" (last commit by a human 2 years ago).
    - [Jaxli](https://github.com/laraboost/jaxli) - It's "still in development" (last commit 2 years ago).
    - [Laraboost](https://laraboost.com) - No HTTPS and redirects to another domain.
    - [Erik Campobadal](https://erik.cat) - Redirects to GitHub.
    - [Crypto Contributors](https://crypto-contributors.netlify.com) - Has almost no content.
    - [Create a Sticky Footer Using Tailwind CSS](https://jimshannon.me/blog/create-a-sticky-footer-using-tailwind-css) - Dead link.
    - [Jim Shannon](https://jimshannon.me) - Dead link.
    - [Gusts](https://gustscss.com) - Dead link.

**Notes**

- To have this awesome list featured on [awesome](sindresorhus/awesome), you still need to add `awesome` and `awesome-list` to this repository's topics, and I think that's all.
- I think there are a couple of items currently in the list that are not exactly awesome, but I did not remove any (except the ones I listed above). I think an objective cleanup would be welcome.

> If you want your list to be included on awesome, **try to only include actual awesome stuff in your list. After all, it's a curation, not a collection**.
> - *[awesome guidelines](https://github.com/sindresorhus/awesome/blob/master/awesome.md#the-awesome-manifesto)*

---

<details>
    <summary><code>awesome-lint</code> before the changes</summary>
&nbsp;
&nbsp;
<pre>
    readme.md:27:3
    ×    1:1    The repository should have "awesome" as a GitHub topic                                remark-lint:awesome/github
    ×    1:1    The repository should have "awesome-list" as a GitHub topic                           remark-lint:awesome/github
    ×    1:1    License was not detected by GitHub                                                    remark-lint:awesome/github
    ×   27:3    Link to https://gustscss.com/ is dead                                                 remark-lint:no-dead-urls
    ×   27:33   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   32:69   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   33:66   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   34:54   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   38:82   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   42:40   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   59:46   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   60:51   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   62:70   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   63:54   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   66:50   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   67:73   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×   81:3    Link to https://anifty.co is dead                                                     remark-lint:no-dead-urls
    ×   94:3    Link to https://jimshannon.me is dead                                                 remark-lint:no-dead-urls
    ×  120:3    Link to https://hellosun.brussels/en/ is dead                                         remark-lint:no-dead-urls
    ×  122:3    Link to https://www.faruno.co is dead                                                 remark-lint:no-dead-urls
    ×  122:34   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  130:39   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  131:36   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  133:39   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  134:42   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  135:51   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  147:59   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  148:55   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  149:83   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  150:87   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  151:61   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  152:57   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  165:62   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  206:72   List item description must end with proper punctuation                                remark-lint:awesome/list-item
    ×  207:64   List item description must end with proper punctuation                                remark-lint:awesome/list-item
    ×  212:65   List item description must end with proper punctuation                                remark-lint:awesome/list-item
    ×  214:58   List item description must start with valid casing                                    remark-lint:awesome/list-item
    ×  216:74   List item description must end with proper punctuation                                remark-lint:awesome/list-item
    ×  217:114  List item description must end with proper punctuation                                remark-lint:awesome/list-item
    ×  218:67   List item description must end with proper punctuation                                remark-lint:awesome/list-item
    ×  219:65   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  222:59   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  223:50   List item link and description must be separated with a dash                          remark-lint:awesome/list-item
    ×  230:90   Link to https://codepen.io/adamwathan/pen/RxWrZr is dead                              remark-lint:no-dead-urls
    ×  240:3    Link to https://jimshannon.me/blog/create-a-sticky-footer-using-tailwind-css is dead  remark-lint:no-dead-urls
    ×  241:3    Link to https://codepen.io/joshmanders/pen/PQQBoR is dead                             remark-lint:no-dead-urls
    ×  244:89   Link to https://codepen.io/drehimself/full/vpeVMx is dead                             remark-lint:no-dead-urls
</pre>
</details>

<details>
    <summary><code>awesome-lint</code> after the changes</summary>
&nbsp;
&nbsp;

<pre>
readme.md:114:3
×    1:1  The repository should have "awesome" as a GitHub topic       remark-lint:awesome/github
×    1:1  The repository should have "awesome-list" as a GitHub topic  remark-lint:awesome/github
×    1:1  License was not detected by GitHub                           remark-lint:awesome/github
×  114:3  Link to https://hellosun.brussels is dead                    remark-lint:no-dead-urls
×  236:5  Link to https://codepen.io/adamwathan/pen/RxWrZr is dead     remark-lint:no-dead-urls
×  238:5  Link to https://codepen.io/drehimself/full/vpeVMx is dead    remark-lint:no-dead-urls
×  244:3  Link to https://codepen.io/joshmanders/pen/PQQBoR is dead    remark-lint:no-dead-urls
</pre>

**Note**: those links are not actually dead (see https://github.com/transitive-bullshit/check-links/issues/4)
</details>

### CODE REVIEW

**Comment by joshmanders** [comment]
Wow @hawezo this is awesome! I was just putting on my todo list to do just this stuff next week. I highly appreciate you stepping in!

I'll look over everything here in a few, just saw the notification and wanted to reply right away!

**Comment by hawezo** [comment]
@joshmanders I've been able to finish the PR this afternoon. Here is a summary of what I have done:

- I reorganized categories again, changing names that I found were more adapted
- I added emojis to better identify resources at a glance
- I updated the contributing guidelines

Although we've previously agreed on keeping all categories first-level, after working on it I thought it would be better if some categories were *Resources* sub-categories. I think the result is well organized and maintenable.

I add stricter rules to the contributing guidelines, and updated the category descriptions and rules. 

I'm again obviously open to any change you think would be necessary. Thanks!

**Comment by joshmanders** [comment]
LGTM 👍

**Comment by m1guelpf** [comment]
@hawezo Thank you a lot for taking the time to do this ❤️

**Pull request merged**
