### PR TITLE
added(template): Pinx

### PR DESCRIPTION
**Pull request by Linko91**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Pinx | https://themeforest.net/item/pinx-vuejs-admin-template/47799543 |

Admin template crafted with Vue 3 + TypeScript, developer-friendly, and designed with Naive UI and Tailwind CSS. Nuxt compatible.

---

- [x ] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by joshmanders** [comment]
I agree with you @innocenzi. Sorry @Linko91.

**Comment by Linko91** [comment]
Sorry, I didn't want to go beyond the rules, I had seen paid products in the list so I thought it was allowed to upload this type of product. No problem 👍

**Comment by Linko91** [comment]
I simply saw in the list of templates, one that says "Paid" in the description but I could be wrong.

**Comment by joshmanders** [comment]
Started a PR adding it in #532. If you notice anymore don't hesitate to comment on that PR with them and I'll add it in to be removed. Thanks again @Linko91!

**Pull request closed without merging**
