### PR TITLE
adds Box Shadows Generator

### PR DESCRIPTION
**Pull request by diomed**
| Name                 | Link                 |
| -------------------- | -------------------- |
| _Box Shadows Generator_ | _https://manuarora.in/boxshadows_ |

_Resource description here_

---

- [ + ] My item is in the right category
- [ +] My item is logically grouped below similar items
- [ +] My item's name and description respects the conventions of the list
- [ +] My item is awesome
- [ +] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [ +] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by joshmanders** [comment]
I get a 404 when I go to the page.

**Comment by diomed** [comment]
I put good link, but forgot s here in comments.

**Comment by diomed** [comment]
?

**Comment by diomed** [comment]
?

**Review by joshmanders — APPROVED** [review]

**Pull request merged**
