### PR TITLE
add(tools): Tailiscope.nvim

### PR DESCRIPTION
**Pull request by DanielVolchek**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Tailiscope.nvim | https://github.com/danielvolchek/tailiscope.nvim |

Tailiscope nvim is a tool I built that converts the popular tailwind css cheatsheet format into a form that can be accessed directly within neovim as an extension to the very popular [telescope.nvim](https://github.com/nvim-telescope/telescope.nvim) plugin

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by innocenzi** [comment]
Can you group your item and rename the PR according to the contribution guidelines, which you checked?

**Comment by DanielVolchek** [comment]
Done!

**Comment by innocenzi** [comment]
Your project should be below "Impulse.dev" to group them by emoji :) I would do it but it's inconvenient on GitHub UI.

**Comment by DanielVolchek** [comment]
Sorry about that! I thought I put it their initially when I forked since it was near the other cheat sheets but I thought I moved it before I PRed. My bad 😅

**Review by innocenzi — APPROVED** [review]

**Pull request merged**
