### PR TITLE
add(components): Motion Primitives 

### PR DESCRIPTION
**Pull request by viruop**
| Name                 | Link                 |
| -------------------- | -------------------- |
| Motion Primitives | https://motion-primitives.com |

Beautifully designed motion components built using Tailwind CSS and Framer Motion
---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by innocenzi — CHANGES_REQUESTED** [review]
Can you shorten the description to a single sentence please?

**Comment by viruop** [comment]
Hi @innocenzi  I've made some changes. Could you please take a look and merge them? Thanks!

**Comment by innocenzi** [comment]
Thanks!

**Comment by joshmanders** [comment]
@innocenzi @viruop Great library, would we benefit here from mentioning that they're React components? I don't have a lot of experience with Framer so maybe that's enough of a hint it's React, but the description doesn't mention React at all and at first glance I personally thought this was a library for Tailwind itself not a React library so I got a bit sad when I realized I couldn't use it in Vue.

**Comment by viruop** [comment]
> @innocenzi @viruop Great library, would we benefit here from mentioning that they're React components? I don't have a lot of experience with Framer so maybe that's enough of a hint it's React, but the description doesn't mention React at all and at first glance I personally thought this was a library for Tailwind itself not a React library so I got a bit sad when I realized I couldn't use it in Vue.

Thanks for your feedback! Could you please reopen the PR so that I can update the description?

**Comment by joshmanders** [comment]
@viruop probably be easier to just submit a new PR.

**Comment by viruop** [comment]
> @viruop probably be easier to just submit a new PR.

Please review the [PR](https://github.com/aniftyco/awesome-tailwindcss/pull/570)

**Pull request merged**
