### PR TITLE
add(librairies): form elements

### PR DESCRIPTION
**Pull request by csscoderRU**
added Component library

| Name                 | Link                 |
| -------------------- | -------------------- |
| _Form elements with states_ | _https://tailwind.csscoder.pro_ |

_Resource description here_
- Form elements library made with Tailwind CSS, include states as loading, error, disabled.
---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Review by innocenzi — CHANGES_REQUESTED** [review]
Can you review the description? I don't think it should contain "include states as loading, error, disabled."

**Comment by csscoderRU** [comment]
> Can you review the description? I don't think it should contain "include states as loading, error, disabled."

Hi, could you check my last update?

**Comment by joshmanders** [comment]
This seems lacking, do you plan to put more stuff on it, or is it just a couple buttons and input fields?

Not to be rude, but it doesn't seem very awesome.

**Comment by csscoderRU** [comment]
> This seems lacking, do you plan to put more stuff on it, or is it just a couple buttons and input fields?
> 
> Not to be rude, but it doesn't seem very awesome.

yes I planing add new styles for existing elements, and add new elements (for example radio, checkbox)

**Comment by csscoderRU** [comment]
The main goal provides a base conception (give a base list of classes names). Having a structured list of class names developer himself can add some changes. It will take less time than write from scratch.

**Comment by joshmanders** [comment]
> > This seems lacking, do you plan to put more stuff on it, or is it just a couple buttons and input fields?
> > Not to be rude, but it doesn't seem very awesome.
> 
> yes I planing add new styles for existing elements, and add new elements (for example radio, checkbox)

Ok, we're gonna close this in until you flesh out a bit more. The list is long and we want to make sure that stuff that does get added is truly awesome.

We just want to keep from adding things that are new and lacking of content, just to have them never get touched after those few things get added. Adds burden on us maintainers of the list to make sure that stuff on the list is truly awesome and being maintained.

Once you've fleshed it out a bit more, feel free to resubmit the PR.

**Pull request closed without merging**
