### PR TITLE
add(plugins): tailwindcss-container-query

### PR DESCRIPTION
**Pull request by dgknca**
| Name                 | Link                 |
| -------------------- | -------------------- |
| tailwindcss-container-query | [_Resource link here_](https://github.com/dgknca/tailwindcss-container-query) |

A plugin that provides CSS Container Queries for tailwindcss.

---

- [x] My item is in the right category
- [x] My item is logically grouped below similar items
- [x] My item's name and description respects the conventions of the list
- [x] My item is awesome
- [x] My item is in line with the [Tailwind brand usage guidelines](https://tailwindcss.com/brand#usage)
- [x] I have read and followed the [contribution guidelines](https://github.com/aniftyco/awesome-tailwindcss/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by innocenzi** [comment]
Can you remove that `Content` header?

**Comment by dgknca** [comment]
I didn't add it. It is adding automatically every time when I save vscode. I managed to delete it by editing it with notepad.

**Comment by dgknca** [comment]
the icon is corrected now

**Review by innocenzi — APPROVED** [review]

**Comment by innocenzi** [comment]
It's one of your VSC extensions. Thanks!

**Pull request merged**
